project_id = "blwnzwkkykaobmclsvxg"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[functions.dental-image-analysis]
verify_jwt = false

[functions.process-dental-upload]
verify_jwt = false

[functions.generate-dental-report]
verify_jwt = false