project_id = "blwnzwkkykaobmclsvxg"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[functions.google-auth-test]
verify_jwt = false

[functions.dental-analysis-v2]
verify_jwt = false

[functions.dental-upload-handler]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.vertex-gemini-test]
verify_jwt = false