// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blwnzwkkykaobmclsvxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsd256d2treWthb2JtY2xzdnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTM2NTksImV4cCI6MjA3MDg2OTY1OX0.SQXqE9wo_-ABNrWMtZCMPqRFvA0-cCoM_8BkiG8F8QQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});