// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yugxuqtdegjowdhktxxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Z3h1cXRkZWdqb3dkaGt0eHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDM0NTMsImV4cCI6MjA2ODA3OTQ1M30.OfZMz8CoUw7dFtdetgHa2N_A0hsMpgOSl2sV0p0_oVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});